server: 
  port: 3344 
  
spring:
  application:
    name:  springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaoshi1994/springCloud-config.git   #GitHub上面的git仓库名字
          username: 2437766749@qq.com
          password: Shfeng941021
 

